version: '3.8'
services:
  portfolio:
    build: .
    ports:
      - "81:3000"
    networks:
      - web
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portfolio.rule=Host(`tstephan.fr`)"
    - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
  restart: unless-stopped
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./certs:/certs
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true